/-
Circulant determinant — Level A only (empty Fin 0 / n=1 / n=2 a²−b² /
optional n=3 a³+b³+c³−3abc). **Not labelled circulant-det / Fourier.**

status: known-classical, formalize-only, **no novelty claim**.
Mathlib v4.10.0 has `Matrix.circulant` / `circulant_apply` /
`Matrix.det` / `det_isEmpty` / `det_fin_one` / `det_fin_two` /
`det_fin_three` and ZERO named circulant determinant /
`det_circulant` / `circulant_det` / `circulantDet`. Completing the
Level A empty / n=1 / n=2 glue is the gap this ticket lands. The
Level B namesake `det_circulant` (DFT / primitive-root product on
`Fin n` over `ℂ`) is **out of this ticket** and is **not** sorry-ed.
Fourier / pfaffian / Kirchhoff extras are residual of this id.

Pin: `catalog/problems/circulant-det/STATEMENT.md` (OPE-1206;
Scout OPE-1200 prime; Director OPE-1205). Encoding: Mathlib
`Matrix.circulant` + `Matrix.det` on `Fin n` over a commutative
ring. Zero `sorry`. Do not import `Archive.*`.

This is **not** `det_vandermonde` (`LinearAlgebra/Vandermonde.lean`
L69) — already Mathlib; a different identity. **USE `circulant` /
`det` / `det_isEmpty` / `det_fin_one` / `det_fin_two` as glue; do
not re-prove them; do not cite Vandermonde as the circulant
formula.** This is **not** Cauchy–Binet (`ProofLab/CauchyBinet.lean`,
PR #117). This is **not** Hadamard determinant inequality
(`ProofLab/HadamardDet.lean`, PR #115). This is **not** Schur
product (`ProofLab/SchurProduct.lean`, PR #129). This is **not**
Lamé (`ProofLab/LameEuclid.lean`, PR #130). This is **not**
Wantzel / `IsConstructible` / Abel–Ruffini / `IsSolvableByRad`.
Do not re-prime the consumed mill. Leave OPE-403 alone.

v1 is `det (circulant v)` on `Fin n` over a commutative ring.
Finite `Fin n` is load-bearing. `CommRing` for Level A is
load-bearing (no `ℂ` required on Level A). `circulant` / `det`
hypotheses are load-bearing.

Level A: `Fin 0` is `det_isEmpty` (`det = 1`). `Fin 1`:
`circulant v 0 0 = v (0-0) = v 0`, and `det_fin_one`. `Fin 2`:
subtraction on `Fin 2` yields the symmetric `[[a,b],[b,a]]` with
`a = v 0`, `b = v 1`; `det_fin_two` gives `a² − b²`. Optional
`n = 3`: expand `det_fin_three` to `a³+b³+c³−3abc`. **Not**
labelled circulant-det.

Transcribed classical argument (circulant as a polynomial in the
cycle matrix; small-n Leibniz expansion). Compact form: Wikipedia
*Circulant matrix* (determinant / eigenvalues). Textbook: Davis,
*Circulant Matrices*. Type pin: `Matrix.circulant` / `Matrix.det` /
`Fin n`. `det_vandermonde` is a different already-in identity.
Cauchy–Binet and Hadamard det are different consumed theorems.
No novelty claim. Default no claim.
-/
import Mathlib.LinearAlgebra.Matrix.Circulant
import Mathlib.LinearAlgebra.Matrix.Determinant.Basic
import Mathlib.Tactic

set_option linter.unusedVariables false

open Matrix

namespace ProofLab.CirculantDet

variable {R : Type*} [CommRing R]

/-! ## Level A: empty / n=1 / n=2 a²−b² / optional n=3
(not labelled circulant-det / Fourier) -/

/-- Empty `Fin 0`: determinant of the empty circulant is `1`.
Uses `det_fin_zero` / `det_isEmpty`; does **not** re-prove them.
Glue; **not** labelled circulant-det. -/
theorem det_circulant_fin_zero (v : Fin 0 → R) :
    det (circulant v) = 1 :=
  det_fin_zero

/-- `n = 1`: the unique entry is `v 0`. Uses `det_fin_one` and
`circulant_apply`; does **not** re-prove them. Glue; **not**
labelled circulant-det. -/
theorem det_circulant_fin_one (v : Fin 1 → R) :
    det (circulant v) = v 0 := by
  rw [det_fin_one, circulant_apply, sub_self]

/-- Wrap on `Fin 2`: `0 − 1 = 1`. Glue for the n=2 expansion;
**not** labelled circulant-det. Uses `zero_sub` / `coe_neg_one`;
does **not** re-prove `circulant`. -/
lemma fin_two_zero_sub_one : (0 : Fin 2) - 1 = 1 := by
  rw [zero_sub]
  apply Fin.ext
  rw [Fin.coe_neg_one, Fin.val_one]

/-- `n = 2`: circulant generated by `(a, b)` is `[[a,b],[b,a]]`,
so the determinant is `a² − b²`. Uses `det_fin_two` /
`circulant_apply`; does **not** re-prove them. Glue; **not**
labelled circulant-det. -/
theorem det_circulant_fin_two (v : Fin 2 → R) :
    det (circulant v) = v 0 ^ 2 - v 1 ^ 2 := by
  rw [det_fin_two]
  simp only [circulant_apply, sub_self, sub_zero, fin_two_zero_sub_one]
  ring

/-- Wrap on `Fin 3`: `0 − 1 = 2`. Glue; **not** labelled
circulant-det. -/
lemma fin_three_zero_sub_one : (0 : Fin 3) - 1 = 2 := by
  rw [zero_sub]
  apply Fin.ext
  rw [Fin.coe_neg_one]
  rfl

/-- Wrap on `Fin 3`: `0 − 2 = 1`. Glue; **not** labelled
circulant-det. -/
lemma fin_three_zero_sub_two : (0 : Fin 3) - 2 = 1 := by
  rw [zero_sub, neg_eq_iff_add_eq_zero]
  apply Fin.ext
  rw [Fin.val_add]
  rfl

/-- Wrap on `Fin 3`: `1 − 2 = 2`. Glue; **not** labelled
circulant-det. -/
lemma fin_three_one_sub_two : (1 : Fin 3) - 2 = 2 := by
  rw [sub_eq_add_neg, ← zero_sub, fin_three_zero_sub_two,
    Fin.ext_iff, Fin.val_add]
  rfl

/-- Optional `n = 3`: circulant generated by `(a, b, c)` has
determinant `a³ + b³ + c³ − 3abc`. Uses `det_fin_three` /
`circulant_apply`; does **not** re-prove them. Extra Level A
identity; **not** labelled circulant-det. **Not** the DFT
namesake. -/
theorem det_circulant_fin_three (v : Fin 3 → R) :
    det (circulant v) = v 0 ^ 3 + v 1 ^ 3 + v 2 ^ 3
      - 3 * v 0 * v 1 * v 2 := by
  rw [det_fin_three]
  simp only [circulant_apply, sub_self, sub_zero,
    fin_three_zero_sub_one, fin_three_zero_sub_two,
    fin_three_one_sub_two]
  ring

/- Residual of this id (comment, **not** `sorry`):
Level B namesake `det_circulant` — product over primitive-root
DFT evaluations `∏ k, ∑ j, v j * ω^(k.val * j.val)` on `Fin n`
over `ℂ`. Fourier / pfaffian / Kirchhoff extras. Out of this
ticket. Do **not** prove `det_vandermonde` as the circulant
formula. -/

end ProofLab.CirculantDet
