/-
Noether normalization lemma, Level A only (identity polynomial-ring
finite-over-self + one-step integral substitution). Formalize-only —
**no novelty claim**, **default no claim**.

status: known-classical, formalize-only.
Mathlib v4.10.0 pin `a719ba5c3115` has `Algebra.FiniteType` /
`Module.Finite` / `Algebra.IsIntegral.finite` /
`Algebra.finite_iff_isIntegral_and_finiteType` / `MvPolynomial` /
`aeval` / `AlgebraicIndependent` as **infra**. ZERO named Noether
normalization / `exists_integral_over_mvPolynomial` under `Mathlib/`
or `Archive/`. Completing the identity + one-step glue is the gap.
Do **not** import `Archive.*`.

Pin: `catalog/problems/noether-normalization/STATEMENT.md` (OPE-1073;
Scout OPE-1062 leftover slot #2; Director OPE-1072). Encoding:
`Field k` + `Algebra.FiniteType` + `MvPolynomial` + `Module.Finite`.
Prefer `CommRing A` / `Algebra k A`. Zero `sorry`.
Do **not** label the theorems Noether. Level B namesake
`noether_normalization` (induction + change of variables) is
**out of this ticket**, not sorry-ed.

This is **not** Hilbert's basis theorem (already Mathlib; finite
generation of *ideals*, a different theorem).
This is **not** `Algebra.IsIntegral.finite` /
`Module.Finite ↔ IsIntegral ∧ FiniteType` (already Mathlib — infra;
USE, do not re-prove).
This is **not** primitive element / Galois correspondence /
Artin–Tate / Nullstellensatz / Nakayama (already Mathlib).
This is **not** going-up / lying-over / Krull PIT (leftover-risk of
this id; do not prove).
This is **not** Mason–Stothers / Descartes / CNS / Schwartz–Zippel /
Alon–Füredi.
This is **not** frobenius-real-division (associative real division;
PR #105 Level A).
This is **not** krenn-gu / hou-zeng-pfc / sun-135.
Leave OPE-403 alone.

Level A (this module, **not** labelled Noether):
1. Identity polynomial-ring case: `MvPolynomial σ k` is
   `Module.Finite` over itself (identity `aeval` / generators = 1).
   Glue already-upstream `Module.Finite.self` / `aeval_X_left`.
2. One-step integral substitution: adjoining one integral element
   (or the quotient by one monic relation) is `Module.Finite` over
   the base. Use `Algebra.IsIntegral.finite` — **do not re-prove**
   integral + finite-type ⇒ module-finite.

Level B namesake `noether_normalization`
  `∃ d y, AlgebraicIndependent k y ∧ Module.Finite (MvPolynomial (Fin d) k) A`
is **out of this ticket**. Infinite-`k` linear change is the v1 cap
if a later namesake appears; finite-`k` power substitution is residual.
Honest residual, not `sorry`.

Transcribed classical Noether 1926 / Atiyah–Macdonald Theorem 5.16 /
Eisenbud Theorem 13.3. No novelty claim. Default no claim.
-/
import Mathlib.Algebra.MvPolynomial.Basic
import Mathlib.RingTheory.AdjoinRoot
import Mathlib.RingTheory.FiniteType
import Mathlib.RingTheory.Finiteness
import Mathlib.RingTheory.IntegralClosure.IsIntegralClosure.Basic

set_option linter.unusedVariables false

open scoped Classical

noncomputable section

namespace ProofLab.NoetherNormalization

/-! ## Glue (already-upstream identity / finiteness; not labelled Noether) -/

/-- Mathlib `MvPolynomial.aeval_X_left`. Identity evaluation on the
indeterminates. Glue, **not** labelled Noether. Do **not** re-prove. -/
theorem aeval_X_left_glue {σ k : Type*} [Field k] :
    MvPolynomial.aeval (MvPolynomial.X : σ → MvPolynomial σ k) =
      AlgHom.id k (MvPolynomial σ k) :=
  MvPolynomial.aeval_X_left

/-- Mathlib `Module.Finite.self`. A ring is module-finite over itself
(generated by `1`). Glue, **not** labelled Noether. Do **not** re-prove. -/
theorem module_finite_self_glue (R : Type*) [Semiring R] : Module.Finite R R :=
  Module.Finite.self R

/-- Mathlib `Algebra.FiniteType.self`. Glue, **not** labelled Noether. -/
theorem finiteType_self_glue (R : Type*) [CommSemiring R] : Algebra.FiniteType R R :=
  Algebra.FiniteType.self R

/-- Mathlib `Algebra.IsIntegral.finite`. Integral + finite-type ⇒
module-finite. Glue, **not** labelled Noether. **Do not re-prove.** -/
theorem isIntegral_finite_glue {k A : Type*} [CommRing k] [CommRing A] [Algebra k A]
    [Algebra.IsIntegral k A] [Algebra.FiniteType k A] : Module.Finite k A :=
  Algebra.IsIntegral.finite

/-! ## Level A.1 — identity polynomial-ring case (not labelled Noether) -/

/-- The polynomial ring is module-finite over itself via the identity
`aeval`. Generators = `{1}`. **Not** labelled Noether. -/
theorem mvPolynomial_module_finite_self {σ k : Type*} [Field k] :
    Module.Finite (MvPolynomial σ k) (MvPolynomial σ k) :=
  module_finite_self_glue _

/-- The polynomial ring is finite-type as an algebra over itself.
**Not** labelled Noether. -/
theorem mvPolynomial_finiteType_self {σ k : Type*} [Field k] :
    Algebra.FiniteType (MvPolynomial σ k) (MvPolynomial σ k) :=
  finiteType_self_glue _

/-- Already-upstream: finitely many indeterminates ⇒ finite-type over the
coefficient field. Glue `Algebra.FiniteType.mvPolynomial`. **Not**
labelled Noether. This is **not** module-finite over `k` (unless `σ`
is empty). -/
theorem mvPolynomial_finiteType {σ k : Type*} [Field k] [Finite σ] :
    Algebra.FiniteType k (MvPolynomial σ k) :=
  Algebra.FiniteType.mvPolynomial k σ

/-! ## Level A.2 — one-step integral substitution (not labelled Noether) -/

/-- Adjoining one integral element is finite-type over the base.
Glue `Subalgebra.fg_adjoin_finset` + `Subalgebra.fg_iff_finiteType`.
**Not** labelled Noether. -/
theorem adjoin_integral_finiteType {k A : Type*} [Field k] [CommRing A] [Algebra k A]
    (x : A) : Algebra.FiniteType k (Algebra.adjoin k ({x} : Set A)) :=
  (Subalgebra.fg_iff_finiteType _).mp
    (Subalgebra.fg_def.2 ⟨{x}, Set.finite_singleton x, rfl⟩)

/-- Adjoining one integral element is an integral algebra over the base.
Glue `adjoin_le_integralClosure` + `le_integralClosure_iff_isIntegral`.
**Not** labelled Noether. -/
theorem adjoin_integral_isIntegral {k A : Type*} [Field k] [CommRing A] [Algebra k A]
    (x : A) (hx : IsIntegral k x) :
    Algebra.IsIntegral k (Algebra.adjoin k ({x} : Set A)) :=
  le_integralClosure_iff_isIntegral.mp (adjoin_le_integralClosure hx)

/-- One-step: adjoining one integral element is module-finite over the
base. Uses already-upstream `Algebra.IsIntegral.finite` — **do not
re-prove** integral + finite-type ⇒ module-finite. **Not** labelled
Noether. -/
theorem adjoin_integral_module_finite {k A : Type*} [Field k] [CommRing A] [Algebra k A]
    (x : A) (hx : IsIntegral k x) :
    Module.Finite k (Algebra.adjoin k ({x} : Set A)) :=
  haveI := adjoin_integral_isIntegral x hx
  haveI := adjoin_integral_finiteType (k := k) (A := A) x
  Algebra.IsIntegral.finite

/-- One-step (quotient form): adjoining a root of a monic polynomial is
module-finite over the base. `AdjoinRoot.finiteType` + integrality of
the root (monic relation) + `Algebra.IsIntegral.finite`. **Not**
labelled Noether. -/
theorem adjoinRoot_monic_module_finite {k : Type*} [Field k] {f : Polynomial k} (hf : f.Monic) :
    Module.Finite k (AdjoinRoot f) := by
  haveI : Algebra.FiniteType k (AdjoinRoot f) := AdjoinRoot.finiteType f
  haveI : Algebra.IsIntegral k (AdjoinRoot f) := by
    refine ⟨fun y => ?_⟩
    have mem : y ∈ Algebra.adjoin k ({AdjoinRoot.root f} : Set (AdjoinRoot f)) := by
      rw [AdjoinRoot.adjoinRoot_eq_top]
      trivial
    exact IsIntegral.of_mem_of_fg _
      (IsIntegral.fg_adjoin_singleton (AdjoinRoot.isIntegral_root' hf)) y mem
  exact Algebra.IsIntegral.finite

/-
## Residual (not sorry)

Level B namesake `noether_normalization` is **out of this ticket**:

  theorem noether_normalization
      (k A : Type*) [Field k] [CommRing A] [Algebra k A]
      [Algebra.FiniteType k A] :
      ∃ (d : ℕ) (y : Fin d → A),
        AlgebraicIndependent k y ∧
        Module.Finite (MvPolynomial (Fin d) k) A

Classical engine: write `A = k[x₁,…,x_n]`; if the `x_i` are
algebraically independent, done; otherwise a nonzero relation
`F(x₁,…,x_n) = 0`; after a change of variables
(`x_i = y_i + y_n^{m^i}` over infinite `k`, or the Noether power
trick over finite `k`), `y_n` is integral over `k[y₁,…,y_{n-1}]`,
and induction applies. Infinite-`k` linear change is an acceptable
v1 cap; finite-`k` power substitution is residual.

Do **not** `sorry` the namesake. Do **not** prove Hilbert basis /
Nakayama / primitive element / Galois / Artin–Tate / Nullstellensatz /
going-up / lying-over / Krull PIT. Do **not** re-prime mason-stothers /
expander-mixing / frobenius-real-division Level B / krenn-gu /
hou-zeng-pfc / sun-135. Leave OPE-403 alone.
-/

end ProofLab.NoetherNormalization
